### PR TITLE
Add erlexec parameter to set ERTS_LIB_DIR

### PR DESCRIPTION
**Pull request by chrta**
This adds the paramerter "-boot_var ERTS_LIB_DIR /usr/lib/erlang/lib" to erlexec.

### CODE REVIEW

**Comment by fhunleth** [comment]
While I don't necessarily have a problem with adding a `-boot_var` for this, I don't understand why it's needed. I did a search for `ERTS_LIB_DIR` in the Erlang source code and didn't see anything in the boot scripts that references it. Do you know who's adding the reference? I'm wondering if they add anything else.

**Comment by chrta** [comment]
I am new to erlang and elixir, so it is a good idea to check... I will search in my built release in which file `ERTS_LIB_DIR` is referenced and where it comes from.

**Comment by chrta** [comment]
What i investigated:

1. exrm seems not to be involved in the issue with `ERTS_LIB_DIR` It just uses the variable in some shell scripts
2. relx adds the variable to some options in the file relx/src/rlx_prv_assembler.erl:
```erlang
make_boot_script(State, Release, OutputDir, RelDir) ->
    Options = [{path, [RelDir | rlx_util:get_code_paths(Release, OutputDir)]},
               {outdir, RelDir},
               {variables, [{"ERTS_LIB_DIR", code:lib_dir()}]},
               no_module_tests, silent],
```

3. relx calls `rlx_util:make_script` and `systools:make_script`
4. In otp the sasl lib provides `systools:make_script` (in the file otp_src_18.3/lib/sasl/src/systools.erl)
5. In this function systools_make:make_script from the file otp_src_18.3/lib/sasl/src/systools_make.erl is called
6. This calls the function `generate_script(Output, Release, Appls, Flags)`
7. This calls the function `create_mandatory_path(Appls, PathFlag, Variables)`
8. This calls `cr_path/5` and depending on the parameters, differnet things happen here
 1. in case of `{include_erts, false}` the following code is executed: `filename:join(["$ROOT", "lib", to_list(Name), "ebin"])`
 2. in case of `{include_erts, true}` the function `variable_dir` is called which returns the `$ERTS_LIB_DIR` string

I don't know if we could fix my problem in another way by supplying other options to relx/exrm.

My resulting boot scripts rel/hello_world/releases/0.0.1/hello_world.script contain these lines:
If {include_erts, true}, then line 8 is
```erlang
{path,["$ROOT/lib/kernel-4.2/ebin","$ROOT/lib/stdlib-2.8/ebin"]},
```
If {include_erts, false}, then line 8 is
```erlang
{path,["$ERTS_LIB_DIR/kernel-4.2/ebin","$ERTS_LIB_DIR/stdlib-2.8/ebin"]},
```

**Comment by fhunleth** [comment]
Interesting. I use `{include_erts, false}`, but I also specify `{system_libs, "path/to/usr/lib/erlang/lib"}`. I have to do the latter so that relx looks at the crosscompiled version of the Erlang apps when building the release. The boot scripts that I have all specify the `$ROOT` directory which is why I haven't run into this issue. It's good that it doesn't look at `$ERTS_LIB_DIR`, since I remove most of the directory to save space on the root filesystem for Nerves. I could imagine configurations where you'd want to keep a full Erlang install there, so my current feeling is to merge your change with a note. I may also remove the warning if it doesn't exist so that it doesn't confuse Nerves users. I'll think about it some more when I get a chance to actually try things out later today. Thanks for investigating this!

**Comment by fhunleth** [comment]
Sorry for the delay. I squashed the commits, made a minor simplification, added a comment about our conversation above and merged it. Thanks for the contribution!

**Pull request closed without merging**
