### PR TITLE
Setup home directory based on /etc/passwd

### LINKED ISSUE #67: Determine $HOME by using /etc/passwd
It's currently set to `/root` here and in `/etc/passwd`. This is confusing when changing `/etc/passwd` and it doesn't get updated. Also, starting Erlang with a non-root UID should properly set`$HOME` as well.

See getpwuid() when implementing this.

### PR DESCRIPTION
**Pull request by fazibear**
Fixes #67

### CODE REVIEW

**Comment by fhunleth** [comment]
Thanks!

The code looks good. I'd like to have a unit test, but I'm not sure how hard that is. I'm guessing that it's a little tricky, so if it doesn't look obvious to you then I'll take a pass at it when I get a chance today or tomorrow.

**Comment by fazibear** [comment]
I'll also take a look at unit tests, and try to write one. Just for sure, it works just fine, but tested out only on x86.

**Comment by fazibear** [comment]
OK Test works fine. But I figured out that tests suite will not pass on OSX. Default root $HOME is /var/root. I can add `/etc/passwd` with `/root` home directory, but tests will not pass either, grep/sed not work as expected.

**Comment by fhunleth** [comment]
Thanks! I have fixes for the tests on OSX and will update after this.

**Pull request merged**
